### PR TITLE
Added catalan (valencian) translation 

### PR DESCRIPTION
**Pull request by Sappstal**

### CODE REVIEW

**Comment by Sappstal** [comment]
There seems to be something wrong with strings.xml file...

**Comment by ShortDevelopment** [comment]
Ah, yes... you have to escape apostrophes with a backslash:
```xml
<string>abc \' bla</string>
```

**Comment by Sappstal** [comment]
Done! Seems like it's working fine now

**Comment by ShortDevelopment** [comment]
Nice, thanks!

**Pull request merged**
